version: "3.9"
services: 
  app: 
      
      volumes:
       - .:/django
      ports:
       - 8000:8000
      image: djawed22/djawed22:latest
      container_name: django_container 
      command: python manage.py runserver 0.0.0.0:8000

           