name: Django CICD

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt update
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mysite/requirements.txt
    - name: Run Tests
      run: |
        python mysite/manage.py test
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build and push image
      working-directory: mysite 
      run: |
         docker build -f Dockerfile -t="djawed22/repo:latest" .
         docker push djawed22/repo:latest
    - name: connect and run on ec2
      env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          USER_NAME : ${{ secrets.USER  }}
            
      run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
        
            cd /home/ec2-user/Github_dashboard/mysite
            touch hi.txt
          ' 
     
        
